version: "3.6"

services:
  mysql:
    container_name: idus-mysql
    image: "mysql:8.0"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=idus
