spring:
  datasource:
    write:
      hikari:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/idus
        username: root
        password: root
        maximum-pool-size: 10
        connection-timeout: 5000 # 5 secs
    read-only:
      hikari:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/idus
        username: root
        password: root
        maximum-pool-size: 10
        connection-timeout: 5000 # 5 secs

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/idus
    user: root
    password: root

logging:
  level:
    com.idus.hw: debug

springfox:
  documentation:
    swagger-ui:
      enabled: true
